---
version: "2.0"

jobs:
  build:
    working_directory: ~/pkgbuilds
    docker:
      - image: kriansa/pkgbuilds:latest

    steps:
      - checkout

      - restore_cache:
          key: build-cache

      - run:
          name: Update Arch repositories
          command: sudo pacman -Sy

      - run:
          name: Build and deploy packages
          command: bin/ci-build "$(echo $CIRCLE_COMPARE_URL | awk -F '/' '{ print $NF }')"

      - save_cache:
          key: build-cache
          paths:
            - output/db
