---
version: "2.0"

jobs:
  build:
    working_directory: ~/pkgbuilds
    docker:
      - image: kriansa/pkgbuilds:latest

    steps:
      - checkout
      - restore_cache:
          key: build-cache

      - run:
          name: Update repositories
          command: sudo pacman -Sy

      - run:
          name: Build packages
          command: bin/build

      - run:
          name: Deploy packages
          command: bin/deploy-to-s3

      - persist_to_workspace:
          root: .
          paths:
            - output

      - save_cache:
          key: build-cache
          paths:
            - output
